graceTimeOut = "10s"
debug = true
checkNewVersion = false
logLevel = "DEBUG"

[traefikLog]
filePath = "/etc/traefik/traefik.log"
format = "common"

# If set to true invalid SSL certificates are accepted for backends.
# Note: This disables detection of man-in-the-middle attacks so should only be used on secure backend networks.
# Optional
# Default: false
#
# InsecureSkipVerify = true

defaultEntryPoints = ["https"]
#defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
#    [entryPoints.http.redirect]
#    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/certs/ssl.crt"
      keyFile = "/etc/traefik/certs/ssl.key"

[web]
address = ":8080"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "local.wholetale.org"
watch = true
exposedbydefault = true
swarmmode = true

[accessLog]
  filePath = "/etc/traefik/access.log"
  format = "json"

  [accessLog.filters]
    statusCodes = ["200", "300-302"]
    retryAttempts = true

  [accessLog.fields]
    defaultMode = "keep"
    [accessLog.fields.names]
      "ClientUsername" = "drop"

    [accessLog.fields.headers]
      defaultMode = "keep"
      [accessLog.fields.headers.names]
        "User-Agent" = "redact"
        "Authorization" = "drop"
        "Content-Type" = "keep"
